### ISSUE TITLE
PETools detected as malware

### ISSUE THREAD

**Issue by minexew** [petoolse/petools#7]
See https://www.virustotal.com/#/file/8fd1a1cc1a253fd58693c181895d392ba20fc2a638aaecbc2e8f5d004db8fc27/detection
Why is this?

**Comment by upiter** [comment]
# Generic answer
You may see many false detections because **antivirus technologies suck**.

# More complex answer

As you can see, PE Tools main **executable is not packed**, code is clean, no virtual machines, no encrypted code parts, no obfuscation. But many antivirus engines can't handle even such easy case.

The main reason why AV could treat PE Tools as risky software because of it's [features](https://github.com/petoolse/petools) list:
### PE Editor

- PE and DOS Headers **Editor**
- PE Sections **Editor**
- PE Directory _Viewer_ and **Editor**
- Export Directory **Editor**
- Import Directory **Editor**
- Resource Directory _Viewer_
- Exception Directory _Viewer_
- Relocation Directory _Viewer_
- Debug Directory _Viewer_
- TLS Directory **Editor**
- Load Config Directory **Editor**
- Bound Directory **Editor**

## Process Viewer and Manager

- Show basic process information
- Show process modules

## PE Dumper

- Running process dumper

## PE Rebuilder

- Dump Fixer
- Relocation Wiper
- Resource Directory Rebuilder
- PE file Validation
- Imports Binder
- ImageBase Changer

# Possible solutions
- Inform antivirus company that produced weak antivirus with paranoid engine about false detection: by email or forum
- Trust professional antivirus which doesn't mark PE Tools as threat
- Analyse PE Tools features with disassembler like [Cutter](https://github.com/radareorg/cutter) / [Binary Ninja](https://binary.ninja/) / [IDA](https://www.hex-rays.com/products/ida/index.shtml) and decide yourself
- Don't use PE Tools in real world environment, only in safe VM conditions

**Comment by djdron** [comment]
So where is project source code to view & research ?
Analyse code with disassembler? No, thanks.
What is a reason to place project on GitHub without source?
Chrome/Microsoft antivirus detects it as trojan.
Old version which i have 1.5.800.2006 RC7 [is not detected](https://www.virustotal.com/gui/file/a69025ececf28f13184fd442d0fe0759db4a6b4f192b974f0d83fa54b70a05aa/detection).

**Comment by upiter** [comment]
> So where is project source code to view & research ?

It's not published, sorry.
You may find leaked/published sources of and old version, then fix bugs and add new features by yourself.

> Analyse code with disassembler? No, thanks.

It's your choice. Trust antivirus.

> What is a reason to place project on GitHub without source?

As  an [issue tracker](https://github.com/petoolse/petools/issues/).

> Chrome/Microsoft antivirus detects it as trojan.

We don't care. See [previous answer](#issuecomment-412335255). Just don't use new version.
If you trust Chrome/Microsoft antivirus then remove new PE Tools version and be safe.

> Old version which i have 1.5.800.2006 RC7 is not detected.

Great news. Use it.

**Comment by ada-s4c** [comment]
> > Old version which i have 1.5.800.2006 RC7 is not detected.
> Great news. Use it.

Not ideal for the user, but that's fair.

**Comment by somk** [comment]
已经收到。

**Comment by upiter** [comment]
> Not ideal for the user, but that's fair.

Well, after visiting the link in first post, you can get two lists:

1. Antiviral products that ~suck~ don't do their job well (false detections)
	- Some of them treat PE Tools as "Unsafe", "Possible Threat"
	- Some of them treat PE Tools as "PUP" (Potentially Unwanted Programs)

2. Antiviral products that do their job well (no false detections)

List of products that treat PE Tools as clean software:

- Avira (no cloud)
- Baidu
- CMC
- Cynet
- Cyren
- DrWeb
- F-Secure
- K7AntiVirus
- K7GW
- Kaspersky
- NANO-Antivirus
- Palo Alto Networks
- QuickHeal
- SentinelOne (Static ML)
- TACHYON
- TEHTRIS
- Trapmine
- VBA32
- VirIT
- Zillya
- ZoneAlarm by Check Point
- Zoner

I recommend to read my [first comment](https://github.com/petoolse/petools/issues/7#issuecomment-412335255), especially block "Possible solutions".

I hope that if every confused researcher instead of complaining here, will push AV-companies to do their job well, then we'll have more adequate AV products and services.
